name: Deploy to Docker Compose
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Start Docker Compose
      run: docker-compose up -d
